CREATE SEQUENCE Publisher_seq
INCREMENT BY 1
START WITH 1241440
NOCYCLE ;

CREATE SEQUENCE Author_seq
INCREMENT BY 1
START WITH 1418418
NOCYCLE ;

CREATE SEQUENCE Genre_seq
INCREMENT BY 1
START WITH 1321742
NOCYCLE ;

CREATE SEQUENCE Store_seq
INCREMENT BY 1
START WITH 1
NOCYCLE ;

CREATE SEQUENCE Offer_seq
INCREMENT BY 1
START WITH 1
NOCYCLE ;

CREATE SEQUENCE Person_seq
INCREMENT BY 1
START WITH 113613136
NOCYCLE ;

CREATE SEQUENCE Job_seq
INCREMENT BY 1
START WITH 1
NOCYCLE ;

CREATE SEQUENCE Order_seq
INCREMENT BY 1
START WITH 1
NOCYCLE ;

CREATE SEQUENCE Supplier_seq
INCREMENT BY 1
START WITH 1251712
NOCYCLE ;

CREATE SEQUENCE Supply_seq
INCREMENT BY 1
START WITH 1
NOCYCLE ;

CREATE SEQUENCE Bank_seq
INCREMENT BY 1
START WITH 1
NOCYCLE ;

CREATE SEQUENCE Transaction_seq
INCREMENT BY 1
START WITH 1
NOCYCLE ;


/*
DROP SEQUENCE Publisher_seq;
DROP SEQUENCE Author_seq;
DROP SEQUENCE Genre_seq;
DROP SEQUENCE Store_seq;
DROP SEQUENCE Offer_seq;
DROP SEQUENCE Person_seq;
DROP SEQUENCE Job_seq;
DROP SEQUENCE Order_seq;
DROP SEQUENCE Supplier_seq;
DROP SEQUENCE Supply_seq;
DROP SEQUENCE Bank_seq;
DROP SEQUENCE Transaction_seq;
*/